### PR TITLE
Rebase mh5_stem_cell on ros-industrial/kinetic-devel

### PR DESCRIPTION
**Pull request by geoffreychiou**
The MH50 robot requires the driver to support the dx200 controller, which this branch does not. This PR rebases the mh5_stem_cell branch on the kinetic-devel branch.

We need the mh5_stem_cell branch becauses the WriteSingleIo services are not defined in the upstream repo.

We did a brief test on the mh5 robot with this code and it still worked.

Also I suggest we create a plusone-robotics fork of motoman and keep this code under plusone/something

@gomezc tagging so you know where this is.

@shaun-edwards please review.

### CODE REVIEW

**Comment by shaun-edwards** [comment]
>The MH50 robot requires the driver to support the dx200 controller, which this branch does not. This PR rebases the mh5_stem_cell branch on the kinetic-devel branch.

Do you know what is specifically required to support the dx200.  There are a lot of changes that you may not want to inject.  For example, I believe the new driver requires the robot to be enabled.  As far as I understand, support for the dx200 is just a launch file.

>We did a brief test on the mh5 robot with this code and it still worked.

Did you have to "enable" the robot driver?

>Also I suggest we create a plusone-robotics fork of motoman and keep this code under plusone/something

That's fine.  We can move it AFTER the PR is accepted (lesson learned from last time we did this).

The kinetic test are failing: https://travis-ci.org/shaun-edwards/motoman/jobs/372276584#L3569

**Comment by geoffreychiou** [comment]
> Do you know what is specifically required to support the dx200. There are a lot of changes that you may not want to inject. For example, I believe the new driver requires the robot to be enabled. As far as I understand, support for the dx200 is just a launch file.

I do not know what exactly is needed, but if it is just the launch file that would be great. Will test that out.

> Did you have to "enable" the robot driver?

Yes, that part is annoying but we should be able to automate that from the launch file or add a call to our robot code.

**Comment by geoffreychiou** [comment]
Nevermind, we don't need this.

**Comment by shaun-edwards** [comment]
I went ahead and moved the repository to the `plusone-robotics` org.

**Pull request closed without merging**
